version: '3'

services:
  db:
    container_name: vaultwarden-db
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_LOGIN}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      PGDATA: "/var/lib/postgresql/data/pgdata"
      c: "authentication_timeout=60"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_LOGIN} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G  
    networks:
      - vaultwarden-network

  vaultwarden:
    depends_on:
      - db
    image: vaultwarden/server:1.30.5
    container_name: vaultwarden-server
    ports:
      - 127.0.0.1:61300:80
    environment:
      - DOMAIN=${VW_DOMAIN}
      - DATABASE_URL=postgresql://${POSTGRES_LOGIN}:${POSTGRES_PASS}@db:5432/${POSTGRES_DB}
      - ADMIN_TOKEN=${VW_ADMIN_TOKEN}
      - SHOW_PASSWORD_HINT=true
      - LOGIN_RATELIMIT_MAX_BURST=10
      - LOGIN_RATELIMIT_SECONDS=60
      - ADMIN_RATELIMIT_MAX_BURST=10
      - ADMIN_RATELIMIT_SECONDS=60
      - SENDS_ALLOWED=true
      - EMERGENCY_ACCESS_ALLOWED=false
      - WEB_VAULT_ENABLED=true
      - SIGNUPS_ALLOWED=false
      - SIGNUPS_VERIFY=true
      - SIGNUPS_VERIFY_RESEND_TIME=3600
      - SIGNUPS_VERIFY_RESEND_LIMIT=5
      - SIGNUPS_DOMAINS_WHITELIST=gmail.com,yandex.ru
      - SMTP_HOST=mail.smtp2go.com
      - SMTP_FROM=${SMTP_FROM}
      - SMTP_FROM_NAME=Vaultwarden
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G  
    volumes:
      - vaultwarden:/data
    networks:
      - vaultwarden-network

  pgbackups:
      container_name: vaultwarden-pgbackups
      image: prodrigestivill/postgres-backup-local
      restart: unless-stopped
      volumes:
          - backups:/backups
          - /etc/localtime:/etc/localtime:ro
      environment:
          - POSTGRES_HOST=vaultwarden-db
          - POSTGRES_DB=${POSTGRES_DB}
          - POSTGRES_USER=${POSTGRES_LOGIN}
          - POSTGRES_PASSWORD=${POSTGRES_PASS}
          - POSTGRES_EXTRA_OPTS=-Z6 --schema=public --blobs
          - SCHEDULE=0 0 * * * * #every hour
          - BACKUP_KEEP_DAYS=7
          - BACKUP_KEEP_WEEKS=4
          - BACKUP_KEEP_MONTHS=6
          - HEALTHCHECK_PORT=8080
      depends_on:
          - db
      deploy:
        resources:
          limits:
            cpus: '1'
            memory: 500M
      networks:
      - vaultwarden-network

volumes:
  vaultwarden:
  pg_data:
  backups:
  
networks:
  vaultwarden-network:
    driver: bridge
